### ISSUE TITLE
Cannot Install IPYIDA on Latest IDA7.5 Release

### ISSUE THREAD

**Issue by i-nino** [eset/ipyida#35]
When running the install command given in the instructions, everything apparently installs alright, and I even get the "Installation successful." message, but this is simply not true.  An exception is thrown:

C:\Users\user\AppData\Roaming\Hex-Rays\IDA Pro\plugins\ipyida.py: 'NoneType' object has no attribute 'set_completer_frame'
Traceback (most recent call last):
  File "C:\IDA75\python\3\ida_idaapi.py", line 604, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/user/AppData/Roaming/Hex-Rays/IDA Pro/plugins/ipyida.py", line 11, in <module>
    from ipyida.ida_plugin import PLUGIN_ENTRY, IPyIDAPlugIn
  File "C:\python38\lib\site-packages\ipyida\ida_plugin.py", line 45, in <module>
    _kernel.start()
  File "C:\python38\lib\site-packages\ipyida\kernel.py", line 96, in start
    app.shell.set_completer_frame()
AttributeError: 'NoneType' object has no attribute 'set_completer_frame'

that prohibits the install.  How can I get around this issue, since I've never experienced it before?  Thanks.

**Comment by marc-etienne** [comment]
This is really weird because the error suggest `app.shell` is `None`, but it's clearly set here https://github.com/ipython/ipykernel/blame/master/ipykernel/kernelapp.py#L492 from `kernel.shell` since almost forever, and `app.kernel.shell` is accessed by `ipyida` just before this call (https://github.com/eset/ipyida/blob/master/ipyida/kernel.py#L85). This line was taken from ipykernel here: https://github.com/ipython/ipykernel/blob/master/ipykernel/embed.py#L56

Can you tell me what version of `ipykernel` you have installed? From IDA's console, paste: `import ipykernel;
print(ipykernel.__version__)`.

**Comment by i-nino** [comment]
Sorry for the extremely delayed response, but I've managed to overcome this issue, so feel free to close it since I think it's more of a Python issue than it is w/ the plugin.  Once I run the one-liner, it stores it in the "wrong" directory, at least one that causes the issue above, and appears to be the default one for Python in AppData/Roaming.  Manually moving it into IDA's Plugins directory has it up and running w/o any issues.

**Comment by marc-etienne** [comment]
Thanks for reporting that it works for you now. Cheers and enjoy IPyIDA!
