### ISSUE TITLE
DO NOT USE UTF8 ENCODING STATEMENT, IDA says it only can parse ascii !!!

### ISSUE THREAD

**Issue by lyciumlee** [eset/ipyida#53]
just remove https://github.com/eset/ipyida/blob/master/ipyida/ipyida_plugin_stub.py#L1. It works!
```
# -*- encoding: utf8 -*-
#
# Simple stub to drop in IDA's "plugins" directory.
#
# Copyright (c) 2016-2018 ESET
# Author: Marc-Etienne M.Léveillé <leveille@eset.com>
# See LICENSE file for redistribution.
```

**Comment by marc-etienne** [comment]
Can you enlighten me as to which version of IDA or Python doesn't support encoding header?

**Comment by lyciumlee** [comment]
Macos IDA 7.5

**Comment by lyciumlee** [comment]
Python 3.9.7 (default, Oct 22 2021, 13:39:39) 
[Clang 13.0.0 (clang-1300.0.29.3)] 
IDAPython v7.4.0 final (serial 0)

**Comment by marc-etienne** [comment]
I'm also running IDA on macOS (I was running 7.5 when it was the latest version) and Python 3 and never experienced this. Can you provide more details about the error you get? How do you load `ipyida_plugin_stub.py`? Is it in your `plugins` directory?

If I remove the encoding header, it will fail with Python 2 because of the non-ascii `é` in the author's name.
