### ISSUE TITLE
%open_notebook dependency against jupyter-kernel-proxy

### ISSUE THREAD

**Issue by RobinDavid** [eset/ipyida#57]
Hello @marc-etienne,

First thanks for keeping ipyida up to date :).

I wanted to try the ```%open_notebook``` feature which would be really usefull.
Nonetheless, when testing it the ```pip install jupyter-kernel-proxy``` fails with a no matching distribution found.
Indeed when looking on directly on https://pypi.org there is no such module.
Am I missing something ?

Thank you in advance,
Robin

As a side question: is the version ```jupyter-client<6.1.13``` still required in the setup.py ?

*(tested on IDA 8.1 Linux with Python 3.10)*

**Comment by marc-etienne** [comment]
Hey @RobinDavid  :)

Looks like you found IPyIDA version 2.0 in advance. I was planning a release in the next few weeks. `jupyter-kernel-proxy` is still not publish, but will be really soon together with IPyIDA 2.0.

> As a side question: is the version `jupyter-client<6.1.13` still required in the setup.py ?

Yes I still can't upgrade to the latest because of an upstream bug (jupyter/jupyter_client#831) :-/ That being said it's being working on and we'll be able to use newer version when it's compatible.

Cheers!

**Comment by RobinDavid** [comment]
Haha yes when I saw that I installed ipyida form github to try it! Okay, it did not came to my mind that ``jupyter-kernel-proxy`` was also your module.

Thanks @marc-etienne ! Let me know when it is being release :)
