### ISSUE TITLE
crash with latest IDA pro 8.4

### ISSUE THREAD

**Issue by dummys** [eset/ipyida#65]
Hello,
I don't know how to debug the crash, but using only your plugins on latest ida pro 8.4 crash the program

Oops, IDA has almost crashed! (signum=11) (error 1442)

**Comment by marc-etienne** [comment]
IPyIDA should work with IDA Pro 8.4 (I'm using `8.4.240527`), and also works with the beta releases of 9.0 since version 2.1.

If you'd like me to help find why it doesn't work for you please share the OS, Python version and how you installed the plugin (using the script or manually). Most of time there is something with the Python configuration leading to a crash like this.

**Comment by dummys** [comment]
sure but how can I debug it ? 
I'm on arch linux (upgraded yesterday, latest version of python) installation manually.

**Comment by marc-etienne** [comment]
I'll try to replicate the environment but I'll need to find a coworker with a Linux license so it might take a bit of time.

If I had to guess, I'd say the problem is probably related to the Python Qt bindings. I'd try with an older version of Python (like 3.11). Use `idapyswitch` to change version.

**Comment by dummys** [comment]
yes you are right. As soon as I switch to 3.11 it works. IDA guy can reproduce my bug and they are working on it.
thanks for help.
